language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
services:
  - docker

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.npm

script:
  - cd client && npm install && npm run build && cd ../
  - cd server && sbt stage && cd ../
  - docker build -f Dockerfile -t wadjetz/cumulus .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push wadjetz/cumulus;
    fi
