version: '3'
services:

  cumulus_db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: cumulus
      POSTGRES_USER: cumulus
      POSTGRES_PASSWORD: cumulus
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  cumulus_mailcatcher:
    image: jeanberu/mailcatcher
    ports:
      - 1025:1025 # SMTP
      - 1080:1080 # Web interface

  cumulus_adminer:
    image: adminer
    ports:
        - 5555:8080
